### ISSUE TITLE
thoughts on fifo creation

### ISSUE THREAD

**Issue by cnorthway** [accessibility-oscilloscope/buildroot#9]
currently fifos are being created by the reader program -- this could create weird situations if a writer opens first and tries to open the (nonexistent) pipe. depending on how the writer is set up, it would either fail (not good) or create a normal file (also, not good)

consider creating all fifos at once before starting any programs. could be done with `mkfifo` and the init system

**Comment by jleightcap** [comment]
the plan in `/etc/init.d/S16oscope`, for a chain `p1 -> p2 -> p3`,

```sh
p3 &
p2 &
p1 &
```

`p3` creates the thing it reads from. `pr` then starts and can write to that FIFO.
